services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=CI
      - CHROMEDRIVER_DIR=/usr/bin
    volumes:
      - ./matome_phase1.Tests/TestFiles:/app/matome_phase1.Tests/bin/Debug/net8.0/TestFiles
